repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    - id: isort
      args: ["--profile", "black", --check-only]
-   repo: https://github.com/ambv/black
    rev: 21.5b0
    hooks:
    - id: black
      args:
        - "--config"
        - "./pyproject.toml"
        - "--check"
      language_version: python3.8