FROM nvcr.io/nvidia/pytorch:21.02-py3

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt

RUN pip install future albumentations resnest pretrainedmodels efficientnet-pytorch

COPY . /app

RUN mkdir -p /app/model && curl -OJ https://nx9836.your-storageshare.de/s/HSq8StKLB6WYncy/download && mv hacking_kidney_16934_best_metric.model-384e1332.pth /app/model

ENV PATH /opt/conda/envs/hacking-kidney/bin:$PATH

ENTRYPOINT python3 /app/test.py
